//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 12:18:45 PM PDT 
//


package org.cvrgrid.schiller.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aquiring_user"/>
 *         &lt;element ref="{}aquiring_department"/>
 *         &lt;element ref="{}aquiring_institute"/>
 *         &lt;element ref="{}referring_user"/>
 *         &lt;element ref="{}requesting_institute"/>
 *         &lt;element ref="{}requesting_department"/>
 *         &lt;element ref="{}analyzing_institute"/>
 *         &lt;element ref="{}analyzing_department"/>
 *         &lt;element ref="{}analyzing_user"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aquiringUser",
    "aquiringDepartment",
    "aquiringInstitute",
    "referringUser",
    "requestingInstitute",
    "requestingDepartment",
    "analyzingInstitute",
    "analyzingDepartment",
    "analyzingUser"
})
@XmlRootElement(name = "idu")
public class Idu {

    @XmlElement(name = "aquiring_user", required = true)
    protected AquiringUser aquiringUser;
    @XmlElement(name = "aquiring_department", required = true)
    protected AquiringDepartment aquiringDepartment;
    @XmlElement(name = "aquiring_institute", required = true)
    protected AquiringInstitute aquiringInstitute;
    @XmlElement(name = "referring_user", required = true)
    protected ReferringUser referringUser;
    @XmlElement(name = "requesting_institute", required = true)
    protected RequestingInstitute requestingInstitute;
    @XmlElement(name = "requesting_department", required = true)
    protected RequestingDepartment requestingDepartment;
    @XmlElement(name = "analyzing_institute", required = true)
    protected AnalyzingInstitute analyzingInstitute;
    @XmlElement(name = "analyzing_department", required = true)
    protected AnalyzingDepartment analyzingDepartment;
    @XmlElement(name = "analyzing_user", required = true)
    protected AnalyzingUser analyzingUser;

    /**
     * Gets the value of the aquiringUser property.
     * 
     * @return
     *     possible object is
     *     {@link AquiringUser }
     *     
     */
    public AquiringUser getAquiringUser() {
        return aquiringUser;
    }

    /**
     * Sets the value of the aquiringUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link AquiringUser }
     *     
     */
    public void setAquiringUser(AquiringUser value) {
        this.aquiringUser = value;
    }

    /**
     * Gets the value of the aquiringDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link AquiringDepartment }
     *     
     */
    public AquiringDepartment getAquiringDepartment() {
        return aquiringDepartment;
    }

    /**
     * Sets the value of the aquiringDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AquiringDepartment }
     *     
     */
    public void setAquiringDepartment(AquiringDepartment value) {
        this.aquiringDepartment = value;
    }

    /**
     * Gets the value of the aquiringInstitute property.
     * 
     * @return
     *     possible object is
     *     {@link AquiringInstitute }
     *     
     */
    public AquiringInstitute getAquiringInstitute() {
        return aquiringInstitute;
    }

    /**
     * Sets the value of the aquiringInstitute property.
     * 
     * @param value
     *     allowed object is
     *     {@link AquiringInstitute }
     *     
     */
    public void setAquiringInstitute(AquiringInstitute value) {
        this.aquiringInstitute = value;
    }

    /**
     * Gets the value of the referringUser property.
     * 
     * @return
     *     possible object is
     *     {@link ReferringUser }
     *     
     */
    public ReferringUser getReferringUser() {
        return referringUser;
    }

    /**
     * Sets the value of the referringUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferringUser }
     *     
     */
    public void setReferringUser(ReferringUser value) {
        this.referringUser = value;
    }

    /**
     * Gets the value of the requestingInstitute property.
     * 
     * @return
     *     possible object is
     *     {@link RequestingInstitute }
     *     
     */
    public RequestingInstitute getRequestingInstitute() {
        return requestingInstitute;
    }

    /**
     * Sets the value of the requestingInstitute property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestingInstitute }
     *     
     */
    public void setRequestingInstitute(RequestingInstitute value) {
        this.requestingInstitute = value;
    }

    /**
     * Gets the value of the requestingDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link RequestingDepartment }
     *     
     */
    public RequestingDepartment getRequestingDepartment() {
        return requestingDepartment;
    }

    /**
     * Sets the value of the requestingDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestingDepartment }
     *     
     */
    public void setRequestingDepartment(RequestingDepartment value) {
        this.requestingDepartment = value;
    }

    /**
     * Gets the value of the analyzingInstitute property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyzingInstitute }
     *     
     */
    public AnalyzingInstitute getAnalyzingInstitute() {
        return analyzingInstitute;
    }

    /**
     * Sets the value of the analyzingInstitute property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyzingInstitute }
     *     
     */
    public void setAnalyzingInstitute(AnalyzingInstitute value) {
        this.analyzingInstitute = value;
    }

    /**
     * Gets the value of the analyzingDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyzingDepartment }
     *     
     */
    public AnalyzingDepartment getAnalyzingDepartment() {
        return analyzingDepartment;
    }

    /**
     * Sets the value of the analyzingDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyzingDepartment }
     *     
     */
    public void setAnalyzingDepartment(AnalyzingDepartment value) {
        this.analyzingDepartment = value;
    }

    /**
     * Gets the value of the analyzingUser property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyzingUser }
     *     
     */
    public AnalyzingUser getAnalyzingUser() {
        return analyzingUser;
    }

    /**
     * Sets the value of the analyzingUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyzingUser }
     *     
     */
    public void setAnalyzingUser(AnalyzingUser value) {
        this.analyzingUser = value;
    }

}
