//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 12:18:45 PM PDT 
//


package org.cvrgrid.schiller.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}samplerate"/>
 *         &lt;element ref="{}yres"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "samplerate",
    "yres"
})
@XmlRootElement(name = "resolution")
public class Resolution {

    @XmlElement(required = true)
    protected Samplerate samplerate;
    @XmlElement(required = true)
    protected Yres yres;

    /**
     * Gets the value of the samplerate property.
     * 
     * @return
     *     possible object is
     *     {@link Samplerate }
     *     
     */
    public Samplerate getSamplerate() {
        return samplerate;
    }

    /**
     * Sets the value of the samplerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Samplerate }
     *     
     */
    public void setSamplerate(Samplerate value) {
        this.samplerate = value;
    }

    /**
     * Gets the value of the yres property.
     * 
     * @return
     *     possible object is
     *     {@link Yres }
     *     
     */
    public Yres getYres() {
        return yres;
    }

    /**
     * Sets the value of the yres property.
     * 
     * @param value
     *     allowed object is
     *     {@link Yres }
     *     
     */
    public void setYres(Yres value) {
        this.yres = value;
    }

}
