//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 12:18:45 PM PDT 
//


package org.cvrgrid.schiller.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}patdata"/>
 *         &lt;element ref="{}examdescript"/>
 *         &lt;element ref="{}eventdata"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patdata",
    "examdescript",
    "eventdata"
})
@XmlRootElement(name = "com.xiriuz.sema.xml.schillerEDI.SchillerEDI")
public class ComXiriuzSemaXmlSchillerEDISchillerEDI {

    @XmlElement(required = true)
    protected Patdata patdata;
    @XmlElement(required = true)
    protected Examdescript examdescript;
    @XmlElement(required = true)
    protected Eventdata eventdata;

    /**
     * Gets the value of the patdata property.
     * 
     * @return
     *     possible object is
     *     {@link Patdata }
     *     
     */
    public Patdata getPatdata() {
        return patdata;
    }

    /**
     * Sets the value of the patdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Patdata }
     *     
     */
    public void setPatdata(Patdata value) {
        this.patdata = value;
    }

    /**
     * Gets the value of the examdescript property.
     * 
     * @return
     *     possible object is
     *     {@link Examdescript }
     *     
     */
    public Examdescript getExamdescript() {
        return examdescript;
    }

    /**
     * Sets the value of the examdescript property.
     * 
     * @param value
     *     allowed object is
     *     {@link Examdescript }
     *     
     */
    public void setExamdescript(Examdescript value) {
        this.examdescript = value;
    }

    /**
     * Gets the value of the eventdata property.
     * 
     * @return
     *     possible object is
     *     {@link Eventdata }
     *     
     */
    public Eventdata getEventdata() {
        return eventdata;
    }

    /**
     * Sets the value of the eventdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eventdata }
     *     
     */
    public void setEventdata(Eventdata value) {
        this.eventdata = value;
    }

}
