//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 12:18:45 PM PDT 
//


package org.cvrgrid.schiller.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}startdatetime"/>
 *         &lt;element ref="{}rectype"/>
 *         &lt;element ref="{}job_id"/>
 *         &lt;element ref="{}user_id"/>
 *         &lt;element ref="{}case_id"/>
 *         &lt;element ref="{}order_id"/>
 *         &lt;element ref="{}location"/>
 *         &lt;element ref="{}idu"/>
 *         &lt;element ref="{}aquiringdevice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startdatetime",
    "rectype",
    "jobId",
    "userId",
    "caseId",
    "orderId",
    "location",
    "idu",
    "aquiringdevice"
})
@XmlRootElement(name = "examdescript")
public class Examdescript {

    @XmlElement(required = true)
    protected Startdatetime startdatetime;
    @XmlElement(required = true)
    protected String rectype;
    @XmlElement(name = "job_id", required = true, defaultValue = "")
    protected String jobId;
    @XmlElement(name = "user_id", required = true, defaultValue = "")
    protected String userId;
    @XmlElement(name = "case_id", required = true, defaultValue = "")
    protected String caseId;
    @XmlElement(name = "order_id", required = true, defaultValue = "")
    protected OrderId orderId;
    @XmlElement(required = true)
    protected Location location;
    @XmlElement(required = true)
    protected Idu idu;
    @XmlElement(required = true)
    protected Aquiringdevice aquiringdevice;

    /**
     * Gets the value of the startdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link Startdatetime }
     *     
     */
    public Startdatetime getStartdatetime() {
        return startdatetime;
    }

    /**
     * Sets the value of the startdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Startdatetime }
     *     
     */
    public void setStartdatetime(Startdatetime value) {
        this.startdatetime = value;
    }

    /**
     * Gets the value of the rectype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectype() {
        return rectype;
    }

    /**
     * Sets the value of the rectype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectype(String value) {
        this.rectype = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobId(String value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the caseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * Sets the value of the caseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseId(String value) {
        this.caseId = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link OrderId }
     *     
     */
    public OrderId getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderId }
     *     
     */
    public void setOrderId(OrderId value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the idu property.
     * 
     * @return
     *     possible object is
     *     {@link Idu }
     *     
     */
    public Idu getIdu() {
        return idu;
    }

    /**
     * Sets the value of the idu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Idu }
     *     
     */
    public void setIdu(Idu value) {
        this.idu = value;
    }

    /**
     * Gets the value of the aquiringdevice property.
     * 
     * @return
     *     possible object is
     *     {@link Aquiringdevice }
     *     
     */
    public Aquiringdevice getAquiringdevice() {
        return aquiringdevice;
    }

    /**
     * Sets the value of the aquiringdevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aquiringdevice }
     *     
     */
    public void setAquiringdevice(Aquiringdevice value) {
        this.aquiringdevice = value;
    }

}
