//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 12:18:45 PM PDT 
//


package org.cvrgrid.schiller.jaxb.beans;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.cvrgrid.schiller.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Model_QNAME = new QName("", "model");
    private final static QName _Reason_QNAME = new QName("", "reason");
    private final static QName _Unitperbit_QNAME = new QName("", "unitperbit");
    private final static QName _Rectype_QNAME = new QName("", "rectype");
    private final static QName _Data_QNAME = new QName("", "data");
    private final static QName _Lastname_QNAME = new QName("", "lastname");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Version_QNAME = new QName("", "version");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _Datastype_QNAME = new QName("", "datastype");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _Birthdate_QNAME = new QName("", "birthdate");
    private final static QName _Gender_QNAME = new QName("", "gender");
    private final static QName _UserId_QNAME = new QName("", "user_id");
    private final static QName _Offset_QNAME = new QName("", "offset");
    private final static QName _Ethnic_QNAME = new QName("", "ethnic");
    private final static QName _Vendor_QNAME = new QName("", "vendor");
    private final static QName _Exponent_QNAME = new QName("", "exponent");
    private final static QName _Channelconfiguration_QNAME = new QName("", "channelconfiguration");
    private final static QName _Firstname_QNAME = new QName("", "firstname");
    private final static QName _Units_QNAME = new QName("", "units");
    private final static QName _Unit_QNAME = new QName("", "unit");
    private final static QName _Samplecount_QNAME = new QName("", "samplecount");
    private final static QName _CaseId_QNAME = new QName("", "case_id");
    private final static QName _Step_QNAME = new QName("", "step");
    private final static QName _JobId_QNAME = new QName("", "job_id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.cvrgrid.schiller.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComXiriuzSemaXmlSchillerEDISchillerEDI }
     * 
     */
    public ComXiriuzSemaXmlSchillerEDISchillerEDI createComXiriuzSemaXmlSchillerEDISchillerEDI() {
        return new ComXiriuzSemaXmlSchillerEDISchillerEDI();
    }

    /**
     * Create an instance of {@link Wavedata }
     * 
     */
    public Wavedata createWavedata() {
        return new Wavedata();
    }

    /**
     * Create an instance of {@link ReferringUser }
     * 
     */
    public ReferringUser createReferringUser() {
        return new ReferringUser();
    }

    /**
     * Create an instance of {@link FiltersData }
     * 
     */
    public FiltersData createFiltersData() {
        return new FiltersData();
    }

    /**
     * Create an instance of {@link AnnotationLead }
     * 
     */
    public AnnotationLead createAnnotationLead() {
        return new AnnotationLead();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Hardware }
     * 
     */
    public Hardware createHardware() {
        return new Hardware();
    }

    /**
     * Create an instance of {@link AnalyzingDepartment }
     * 
     */
    public AnalyzingDepartment createAnalyzingDepartment() {
        return new AnalyzingDepartment();
    }

    /**
     * Create an instance of {@link Aquiringdevice }
     * 
     */
    public Aquiringdevice createAquiringdevice() {
        return new Aquiringdevice();
    }

    /**
     * Create an instance of {@link RequestingInstitute }
     * 
     */
    public RequestingInstitute createRequestingInstitute() {
        return new RequestingInstitute();
    }

    /**
     * Create an instance of {@link AquiringDepartment }
     * 
     */
    public AquiringDepartment createAquiringDepartment() {
        return new AquiringDepartment();
    }

    /**
     * Create an instance of {@link AnalyzingInstitute }
     * 
     */
    public AnalyzingInstitute createAnalyzingInstitute() {
        return new AnalyzingInstitute();
    }

    /**
     * Create an instance of {@link AquiringUser }
     * 
     */
    public AquiringUser createAquiringUser() {
        return new AquiringUser();
    }

    /**
     * Create an instance of {@link Resolution }
     * 
     */
    public Resolution createResolution() {
        return new Resolution();
    }

    /**
     * Create an instance of {@link Patdata }
     * 
     */
    public Patdata createPatdata() {
        return new Patdata();
    }

    /**
     * Create an instance of {@link RequestingDepartment }
     * 
     */
    public RequestingDepartment createRequestingDepartment() {
        return new RequestingDepartment();
    }

    /**
     * Create an instance of {@link RhythmGlobal }
     * 
     */
    public RhythmGlobal createRhythmGlobal() {
        return new RhythmGlobal();
    }

    /**
     * Create an instance of {@link Yres }
     * 
     */
    public Yres createYres() {
        return new Yres();
    }

    /**
     * Create an instance of {@link AnalyzingUser }
     * 
     */
    public AnalyzingUser createAnalyzingUser() {
        return new AnalyzingUser();
    }

    /**
     * Create an instance of {@link Eventdata }
     * 
     */
    public Eventdata createEventdata() {
        return new Eventdata();
    }

    /**
     * Create an instance of {@link Examdescript }
     * 
     */
    public Examdescript createExamdescript() {
        return new Examdescript();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link AquiringInstitute }
     * 
     */
    public AquiringInstitute createAquiringInstitute() {
        return new AquiringInstitute();
    }

    /**
     * Create an instance of {@link Textdata }
     * 
     */
    public Textdata createTextdata() {
        return new Textdata();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link AnnotationGlobal }
     * 
     */
    public AnnotationGlobal createAnnotationGlobal() {
        return new AnnotationGlobal();
    }

    /**
     * Create an instance of {@link Pacemaker }
     * 
     */
    public Pacemaker createPacemaker() {
        return new Pacemaker();
    }

    /**
     * Create an instance of {@link Software }
     * 
     */
    public Software createSoftware() {
        return new Software();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Idu }
     * 
     */
    public Idu createIdu() {
        return new Idu();
    }

    /**
     * Create an instance of {@link Samplerate }
     * 
     */
    public Samplerate createSamplerate() {
        return new Samplerate();
    }

    /**
     * Create an instance of {@link Startdatetime }
     * 
     */
    public Startdatetime createStartdatetime() {
        return new Startdatetime();
    }

    /**
     * Create an instance of {@link Height }
     * 
     */
    public Height createHeight() {
        return new Height();
    }

    /**
     * Create an instance of {@link OrderId }
     * 
     */
    public OrderId createOrderId() {
        return new OrderId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "model")
    public JAXBElement<String> createModel(String value) {
        return new JAXBElement<String>(_Model_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reason")
    public JAXBElement<String> createReason(String value) {
        return new JAXBElement<String>(_Reason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unitperbit")
    public JAXBElement<BigDecimal> createUnitperbit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Unitperbit_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rectype")
    public JAXBElement<String> createRectype(String value) {
        return new JAXBElement<String>(_Rectype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data")
    public JAXBElement<String> createData(String value) {
        return new JAXBElement<String>(_Data_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastname")
    public JAXBElement<String> createLastname(String value) {
        return new JAXBElement<String>(_Lastname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<Integer> createDate(Integer value) {
        return new JAXBElement<Integer>(_Date_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<Integer> createTime(Integer value) {
        return new JAXBElement<Integer>(_Time_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datastype")
    public JAXBElement<String> createDatastype(String value) {
        return new JAXBElement<String>(_Datastype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "birthdate")
    public JAXBElement<Integer> createBirthdate(Integer value) {
        return new JAXBElement<Integer>(_Birthdate_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user_id")
    public JAXBElement<String> createUserId(String value) {
        return new JAXBElement<String>(_UserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "offset")
    public JAXBElement<Boolean> createOffset(Boolean value) {
        return new JAXBElement<Boolean>(_Offset_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ethnic")
    public JAXBElement<String> createEthnic(String value) {
        return new JAXBElement<String>(_Ethnic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vendor")
    public JAXBElement<String> createVendor(String value) {
        return new JAXBElement<String>(_Vendor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exponent")
    public JAXBElement<Boolean> createExponent(Boolean value) {
        return new JAXBElement<Boolean>(_Exponent_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "channelconfiguration")
    public JAXBElement<String> createChannelconfiguration(String value) {
        return new JAXBElement<String>(_Channelconfiguration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "firstname")
    public JAXBElement<String> createFirstname(String value) {
        return new JAXBElement<String>(_Firstname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units")
    public JAXBElement<String> createUnits(String value) {
        return new JAXBElement<String>(_Units_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unit")
    public JAXBElement<String> createUnit(String value) {
        return new JAXBElement<String>(_Unit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "samplecount")
    public JAXBElement<Short> createSamplecount(Short value) {
        return new JAXBElement<Short>(_Samplecount_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "case_id")
    public JAXBElement<String> createCaseId(String value) {
        return new JAXBElement<String>(_CaseId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "step")
    public JAXBElement<Boolean> createStep(Boolean value) {
        return new JAXBElement<Boolean>(_Step_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "job_id")
    public JAXBElement<String> createJobId(String value) {
        return new JAXBElement<String>(_JobId_QNAME, String.class, null, value);
    }

}
